### ISSUE TITLE
Unauthenticated aws s3 requests

### ISSUE THREAD

**Issue by KirillovDenis** [nspcc-dev/neofs-s3-gw#219]
We can only use bucket/containers which is owned by s3-gw itself If unauthenticated requests are used (e.g. `--no-sign-request` param in aws cli). It's a little bit odd since we couldn't work with public bucket that was created with authenticated request. The reason is using `owner id` in `pool.ListContainers` to get any bucket and this owner is differ in un/authenticated request. So we get `NoSuchBucket` error.

**Comment by alexvanin** [comment]
Related to https://github.com/nspcc-dev/coredns/issues/1

**Comment by realloc** [comment]
To properly use NNS the S3 gateway must set not only the `Name` attribute, but also `__NEOFS__NAME` to be set as globally unique name set in NNS. The `Name` attribute doesn't have to be unique, but the bucket name and  `__NEOFS__NAME` do.

**Comment by alexvanin** [comment]
> To properly use NNS the S3 gateway must set not only the `Name` attribute, but also `__NEOFS__NAME` to be set as globally unique name set in NNS. The `Name` attribute doesn't have to be unique, but the bucket name and `__NEOFS__NAME` do.

`__NEOFS__NAME` will register domain in `.container` zone. If S3 will require separate zone, then we need:
- set `__NEOFS__ZONE` attribute,
- register `.s3` TLD in target environment (dev-env?)

**Comment by alexvanin** [comment]
After https://github.com/nspcc-dev/coredns/issues/16 it will be possible to map container nice name zones from side chain into internet domains. With https://github.com/nspcc-dev/neofs-sdk-go/pull/84 we can fallback to side chain contract in case of any DNS errors. Let's use that.

## System DNS resolve

Consider you need to access bucket with name `foo`. Right now S3 gate looks over available user containers with name attribute `foo`. But in case of anonymous request, we won't be able to find any containers related to user (because it is anonymous). So S3 can try to do DNS resolve.

It is possible that there is a `foo.container` or `foo.s3` record in NNS contract. NNS contract can be mapped into some domain. To find that check global NeoFS config available from `netmap.NetworkInfo` request. It contains key:value pairs. Look for `SystemDNS` key with the value of `some.domain.org`. 

Note 1: we can define any key:value format for system DNS since it is not part of the specification.

If the record is not available, fallback. 

If the record is available, try to resolve `TXT` records of `foo.some.domain.org`. There should be string representation of container address.

## Fallback
Can be done in separate PR after system DNS resolve. As the fallback, S3 gateway can access NNS contract directly. To do that it requires side chain endpoint in config. For now it is optional.

**Comment by realloc** [comment]
> `__NEOFS__NAME` will register domain in `.container` zone. If S3 will require separate zone, then we need:

I suggest keeping all containers in the same `.container` zone by default. Dedicated zones can be used to implement multitenancy, but that's should be controlled by another mechanisms, outside the gate's main logic.
