### ISSUE TITLE
Bucket not empty

### ISSUE THREAD

**Issue by KirillovDenis** [nspcc-dev/neofs-s3-gw#320]
During tests run sometimes cleanup fails because of `An error occurred (BucketNotEmpty) when calling the DeleteBucket operation: The bucket you tried to delete is not empty`.
I think we currently consider presence some system objects in container as `BucketeNotEmpty` (we need check this) but we should not.

Can reproduce on `test_s3.test_versioning_bucket_multipart_upload_return_version_id` test

**Comment by masterSplinter01** [comment]
The bug raises in cases when we try to delete the bucket with disabled or suspended versioning. 

The test makes a request `ListObjectVersions`, gets a list of objects with not null `VersionId == ObjectId`,  puts the `VersionId` in the next request `DeleteMultipleObjects`, and the gateway doesn't delete the objects because of receiving of incorrect `VersionId` (bucket versioning state is disabled/suspended). 

So, I think we need to make `ListObjectVersions` returning null `VersionId` for objects created in buckets with disabled/suspended versioning.

**Comment by KirillovDenis** [comment]
It seems this issue related to #319

**Comment by masterSplinter01** [comment]
Closed via #322

**Comment by masterSplinter01** [comment]
Closed via #322
