### ISSUE TITLE
Setup GH workflows to run tests

### ISSUE THREAD

**Issue by roman-khimov** [nspcc-dev/neofs-s3-gw#780]
Similar to neofs-node, short run for PRs and complete suite for master (adjust https://github.com/nspcc-dev/s3-tests if needed). Let's try using GH runners for it.

**Comment by MaxGelbakhiani** [comment]
Got S3 tests running on my private branch. The result is not final. I still need to finish the reporting part. So it's not merged.

**Comment by MaxGelbakhiani** [comment]
During the last week, I worked on the implementing allure test reports. 

I try to use the following approach:
1. To use pytest as a test runner to run nosetests (s3 tests are written using nose). 
2. And to use allure in conjunction with pytest.

Additionally on Friday it turned out, that S3-gw fails on building docker image and it could be solved by running `make sync-tree` before `make image`. 

If time allows I'll continue with this activity this week.

**Comment by roman-khimov** [comment]
Fails at the moment
https://github.com/nspcc-dev/neofs-s3-gw/actions/runs/6223383834/job/16889219106

**Comment by roman-khimov** [comment]
Considering as done, but https://github.com/nspcc-dev/s3-tests/issues/39 and https://github.com/nspcc-dev/s3-tests/issues/40
