### ISSUE TITLE
GH workflow for S3 subset of neofs-testcases

### ISSUE THREAD

**Issue by roman-khimov** [nspcc-dev/neofs-s3-gw#782]
While #780 is for S3-specific compatibility suite we also have a set of S3 tests in neofs-testcases which means that this subset must be run as well for this repo. Adjust tests to have this group if needed.

**Comment by MaxGelbakhiani** [comment]
Got S3 tests running on my private branch. The result is not final. I still need to finish the reporting part. So it's not merged.

**Comment by MaxGelbakhiani** [comment]
During the last week, I worked on the implementing allure test reports.

I try to use the following approach:

To use pytest as a test runner to run nosetests (s3 tests are written using nose).
And to use allure in conjunction with pytest.
Additionally on Friday it turned out, that S3-gw fails on building docker image and it could be solved by running make sync-tree before make image.

If time allows I'll continue with this activity this week.

**Comment by roman-khimov** [comment]
Not fixed. #809 tried to fix #780, not this one. Please pay more attention to it.
